import type { Metadata } from "next";
import {  Raleway, } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Quicktrads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
// ${lora.variable}